"""What every metric means, how it is calculated, and what it is worth.

One dictionary, used by both boards, so a metric cannot mean one thing on the
Australia page and another on the club page. Each entry carries a plain-English
definition, the actual calculation, and the caveat a coach should hear before
acting on it. The reliability figure is not hard-coded here - it is read from
reliability.json at build time, so the tooltip always states the measured number
rather than a remembered one.
"""
from __future__ import annotations

# name: (short label, what it means, how it is calculated, the caveat)
DEFS: dict[str, tuple[str, str, str, str]] = {
    # ---- passing volume and quality
    "passes": ("Passes", "How much he is involved in the team's passing.",
               "Passes attempted, per 100 of his own team's on-ball events while he was on the pitch.",
               "Volume, not quality. A deep midfielder in a possession side will always be high."),
    "pass_completion": ("Pass completion", "Share of his passes that found a team-mate.",
                        "Completed passes / passes attempted.",
                        "Rises the shorter and more backward the passing. Read it next to forward-pass share, never alone."),
    "pass_completion_pressed": ("Completion under pressure", "Whether he keeps the ball when an opponent is closing.",
                                "Completed passes / passes attempted, on passes the provider flagged as made under pressure.",
                                "The pressure flag is binary. On the Australia board it is calibrated against measured metres: flagged touches had an opponent a median 2.2m away, unflagged 6.0m."),
    "forward_pass_share": ("Forward-pass share", "How often he chooses to play forward.",
                           "Passes ending more than 2m closer to the opponent goal / all his passes.",
                           "A choice, not a skill. Low is right for some roles; it becomes a weakness only when the team has no other route forward."),
    "passes_fwd": ("Forward passes", "Volume of forward passing.",
                   "Passes ending more than 2m upfield, per 100 team on-ball events.", ""),
    "passes_prog": ("Progressive passes", "Passes that meaningfully advance the ball.",
                    "Completed passes gaining at least 5m and at least 25% of the remaining distance to goal, per 100 team on-ball events.",
                    "The 25% rule makes a 10m pass near the box count the same as a 30m pass from deep, which is the intent."),
    "progressive_share": ("Progressive share", "How much of his passing is progressive.",
                          "Progressive passes / all passes.", ""),
    "entries_f3": ("Final-third entries", "Passes that move the team into the final third.",
                   "Completed passes starting outside and ending inside the final third, per 100 team on-ball events.", ""),
    "passes_into_f3": ("Passes into the final third", "All completed passes landing in the final third.",
                       "Completed passes ending beyond x=80, per 100 team on-ball events.",
                       "Includes passes that started there, unlike final-third entries."),
    "final_third_entry_share": ("Final-third entry share", "How much of their passing from deeper ends up entering the final third.",
                               "Completed passes into the final third / passes attempted from outside it.",
                               "Needs about 239 attempts before it separates players, which most do not reach in a tournament."),
    "entries_box": ("Box entries", "Passes that put the ball in the penalty area.",
                    "Completed passes ending inside the box from outside it, per 100 team on-ball events.", ""),
    "switches": ("Switches of play", "Changing the side the attack is on.",
                 "Completed passes moving the ball more than 30m across the pitch, per 100 team on-ball events.",
                 "A switch is a tool against a compact block; volume alone does not say it was the right ball."),
    "crosses": ("Crosses", "Volume of crossing.",
                "Passes tagged as crosses, per 100 team on-ball events.", ""),
    "cross_completion": ("Cross completion", "Share of crosses that found a team-mate.",
                         "Completed crosses / crosses attempted.",
                         "Needs about 115 crosses before it separates one player from another. Most players never reach that in a tournament."),
    "key_passes": ("Key passes", "Passes that created a shot.",
                   "Passes directly leading to a team-mate's shot, per 100 team on-ball events.", ""),
    "pre_assists": ("Pre-assists", "The pass before the pass that created the shot.",
                    "Completed passes to the player who then made a shot-creating pass, per 100 team on-ball events.",
                    "Credits the build-up rather than only the final ball."),
    # ---- carrying and receiving
    "carries": ("Carries", "How often he moves the ball with his feet.",
                "Carry events, per 100 team on-ball events.", ""),
    "carries_prog": ("Progressive carries", "Carrying that advances the ball.",
                     "Carries gaining at least 5m upfield, per 100 team on-ball events.", ""),
    "carries_into_f3": ("Carries into the final third", "Beating the line by running, not passing.",
                        "Carries starting outside and ending inside the final third, per 100 team on-ball events.",
                        "The carrying counterpart of a line-breaking pass: the player beat the line himself."),
    "carries_into_box": ("Carries into the box", "Running the ball into the penalty area.",
                         "Carries ending inside the box from outside it, per 100 team on-ball events.", ""),
    "dribbles": ("Take-ons", "How often he tries to beat a man.",
                 "Dribble attempts, per 100 team on-ball events.", ""),
    "dribble_success": ("Take-on success", "Share of attempts that beat the man.",
                        "Completed dribbles / dribbles attempted.",
                        "Split-half reliability is only 0.17 here: a player's own take-on rate barely repeats between halves of the same sample. Treat it as description, not skill."),
    "receptions": ("Receptions", "How often the ball comes to him.",
                   "Completed ball receipts, per 100 team on-ball events.", ""),
    "receptions_pressed": ("Receiving under pressure", "How often he takes the ball with an opponent on him.",
                           "Receipts flagged under pressure, per 100 team on-ball events.",
                           "High is a role description - a striker with his back to goal - not a virtue."),
    "retention_under_pressure": ("Keeping it under pressure", "Whether the ball survives when he is pressed.",
                                 "Pressed touches that did not end in a turnover / all pressed touches.",
                                 "Combines passing and receiving under pressure into one rate, which is why it stabilises faster than either alone."),
    "touches_box": ("Touches in the box", "Presence in the penalty area.",
                    "Any on-ball action inside the box, per 100 team on-ball events.", ""),
    "dispossessed": ("Dispossessed", "Losing the ball to a tackle.",
                     "Times tackled out of possession, per 100 team on-ball events.", "Lower is better."),
    "miscontrol": ("Miscontrols", "Losing the ball without a challenge.",
                   "Failed touches, per 100 team on-ball events.", "Lower is better."),
    # ---- shooting
    "shots": ("Shots", "Shot volume.",
              "Non-penalty shots, per 100 team on-ball events.", ""),
    "shot_on_target_share": ("Shots on target", "Share of shots hitting the goal.",
                             "Shots on target / shots.",
                             "REFUSED on this board: split-half reliability is -0.40, meaning a player's rate in one half of the sample tells you nothing about the other. It is noise."),
    "xg": ("Expected goals", "The quality of the chances he got on the end of.",
           "The provider's shot model, summed over his non-penalty shots.", ""),
    "xa": ("Expected assists", "The quality of the chances he created.",
           "The expected-goals value of the shots his passes set up.",
           "Credits the passer with the shooter's shot selection, which is the standard flaw in this metric."),
    "xgot": ("Post-shot xG (xGOT)", "How well the shot was struck, given where it ended up in the goal.",
             "A logistic model on the placement of on-target shots - distance from the centre of the goal, height, and their interaction - with pre-shot xG as an offset so it learns placement rather than chance quality. AUC 0.813 against 0.776 for pre-shot xG alone.",
             "Only defined on shots that were on target, and ball speed is not in the data, so a placed pass and a rising drive to the same spot score the same."),
    # ---- defending
    "pressures": ("Pressures", "How often he closes an opponent down.",
                  "Pressure events, per 100 of the opponent's on-ball events while he was on.",
                  "Only exists on the Australia board: Opta has no pressure event, so the club board cannot show this."),
    "counterpress": ("Counterpressures", "Pressing immediately after losing the ball.",
                     "Pressures within five seconds of a turnover, per 100 opponent on-ball events.", ""),
    "recoveries": ("Recoveries", "Picking up loose balls.",
                   "Ball recoveries, per 100 opponent on-ball events.", ""),
    "interceptions": ("Interceptions", "Reading and cutting out a pass.",
                      "Interceptions, per 100 opponent on-ball events.",
                      "Needs roughly 790 minutes before it separates players. Below that it is mostly the prior."),
    "blocks": ("Blocks", "Getting in the way of a pass or shot.",
               "Blocks, per 100 opponent on-ball events.", ""),
    "clearances": ("Clearances", "Getting the ball away under duress.",
                   "Clearances, per 100 opponent on-ball events.",
                   "Almost pure exposure: it mostly measures how often the team is under siege."),
    "aerials": ("Aerial duels", "How often he contests in the air.",
                "Aerial duels, per 100 opponent on-ball events.", ""),
    "aerial_win": ("Aerial win rate", "Share of aerial duels won.",
                   "Aerials won / aerials contested, shrunk toward the field average for his position.",
                   "Needs about 33 duels before his own data outweighs the prior."),
    "ground_duels": ("Ground duels", "How often he engages on the floor.",
                     "Tackles and challenges, per 100 opponent on-ball events.", ""),
    "ground_duel_win": ("Ground duel win rate", "Share of ground duels won.",
                        "Duels won / duels contested, shrunk toward the field average for his position.",
                        "Split-half reliability 0.29. Engagement rate is the more repeatable half of this skill."),
    "fouls_won": ("Fouls won", "Drawing free kicks.",
                  "Fouls won, per 100 team on-ball events.", ""),
    "fouls_won_f3": ("Fouls won in the final third", "Winning free kicks in dangerous areas.",
                     "Fouls won beyond x=80, per 100 team on-ball events.",
                     "Worth far more than a foul won in your own half: it stops a counter or wins a set piece in a scoring area."),
    "fouls_committed": ("Fouls conceded", "Giving free kicks away.",
                        "Fouls committed, per 100 opponent on-ball events.", "Lower is better."),
    # ---- line-breaking (360 only)
    "bypassed_per_pass": ("Opponents beaten per forward pass", "How many opponents the ball goes past when he plays forward.",
                          "For each completed forward pass, opponents whose position lies between the ball's start and finish and within 10m of the line of the pass, measured from the freeze frame at the moment of the pass.",
                          "Counts only opponents the broadcast camera could see, so it is an undercount. The ranking is stable between an 8m and an 18m corridor."),
}

COMPOSITE_DEFS: dict[str, str] = {
    "Progression": "Moving the ball upfield: forward and progressive passes, progressive carries and entries into the final third.",
    "Security in possession": "Keeping the ball: completion, retention under pressure, and not being dispossessed or miscontrolling.",
    "Creating": "Making chances: box entries, key passes and crossing volume.",
    "Creation": "Making chances: box entries, key passes and crossing volume.",
    "Pressing": "Closing opponents down: pressures and counterpressures per opponent action.",
    "Winning it back": "Regaining possession: recoveries, interceptions, blocks and clearances.",
    "Recovery work": "Regaining possession: recoveries, interceptions, blocks and clearances.",
    "Duels": "Contesting the ball: aerial and ground duel win rates, and how often he engages at all.",
    "Carrying": "Moving the ball with his feet: carries, take-ons and receiving under pressure.",
}
